sudo: required
dist: trusty
language: scala

env:
  - MVN_FLAG=-Pspark-1.6
  - MVN_FLAG=-Pspark-2.0

jdk:
  - oraclejdk7

addons:
  apt:
    sources:
      r-packages-trusty
    packages:
      r-base

cache:
  pip: true
  directories:
    - $HOME/.m2
    - $(npm config get prefix)

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo apt-get -y install libkrb5-dev
  - sudo apt-get -y remove python-setuptools
  - pip install --user --upgrade pip setuptools
  - pip3 install --user --upgrade pip setuptools
  - pip install --user codecov cloudpickle
  - pip3 install --user cloudpickle

install:
  - mvn $MVN_FLAG install -Dskip -DskipTests -DskipITs -Dmaven.javadoc.skip=true -B -V

before_script:
  - pip install --user requests pytest flaky flake8
  - pip3 install --user requests pytest flaky

script:
  - mvn $MVN_FLAG verify -e

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - npm list -g azure-cli --depth=0 || npm install -g azure-cli
  - ./dev/travis-upload-logs.sh
