sudo: required
dist: trusty
language: scala

jdk:
  - oraclejdk7

addons:
  apt:
    sources:
      r-packages-trusty
    packages:
      r-base

cache:
  pip: true
  directories:
    - $HOME/.m2

before_install:
  - pip install --user codecov cloudpickle

install:
  - mvn install -DskipTests=true -DskipITs=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - sudo apt-get -y install python3-pip python-dev
  - pip install --user requests pytest flaky flake8
  - pip3 install --user requests pytest flaky
  - flake8 . --exclude=./target,./resources --ignore=E127,E128

script:
  - mvn verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
